# Generated by Django 5.2 on 2025-05-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_is_admin_user_is_superuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="employee_number",
            new_name="employeeNo",
        ),
    ]
