# Generated by Django 5.2 on 2025-05-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "007_seed_super_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
