# Generated by Django 5.2 on 2025-05-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField(default='2025-01-01')),
                ('requested_asset', models.CharField(max_length=255, null=True)),
                ('requested_user', models.CharField(max_length=255)),
                ('status', models.CharField(default='Good Condition', max_length=255)),
            ],
            options={
                'verbose_name': 'request',
                'verbose_name_plural': 'requests',
                'db_table': 'request',
            },
        ),
    ]
