# Generated by Django 5.2 on 2025-05-27 06:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_rename_asset_tag_asset_asset_tag_and_more"),
        ("requests", "0001_initial"),
        ("users", "0008_user_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="requested_asset",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="assets.asset",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="request",
            name="requested_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="requested_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.user",
            ),
        ),
    ]
