# Generated by Django 5.2 on 2025-05-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_request_id_alter_request_requested_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='action',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
