# Generated by Django 5.2 on 2025-05-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_request_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
