# Generated by Django 5.2 on 2025-05-29 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0007_alter_asset_status"),
        ("requests", "0005_request_check_in_request_check_out_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="status",
        ),
        migrations.AlterField(
            model_name="request",
            name="requested_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.asset",
            ),
        ),
    ]
