# Generated by Django 5.2 on 2025-05-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0006_remove_request_status_alter_request_requested_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="reason",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
