# Generated by Django 5.2 on 2025-05-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Asset_Tag', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('supplier', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'asset',
                'verbose_name_plural': 'assets',
                'db_table': 'asset',
            },
        ),
    ]
