# Generated by Django 5.2 on 2025-06-12 06:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("asset_tag", models.CharField(max_length=255)),
                ("serial_no", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("purchase_cost", models.IntegerField(default=0)),
                ("supplied_date", models.DateTimeField(auto_now_add=True)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(default="Unknown", max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("disposal", "Disposal"),
                            ("good", "Good"),
                            ("damaged", "Damaged"),
                        ],
                        default="good",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "asset",
                "verbose_name_plural": "assets",
                "db_table": "asset",
            },
        ),
    ]
