# Generated by Django 5.2 on 2025-05-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='supplier',
        ),
        migrations.AddField(
            model_name='asset',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(default='Active', max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier_date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
