# Generated by Django 5.2 on 2025-05-27 06:56

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_remove_asset_supplier_asset_department_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="Asset_Tag",
            new_name="asset_tag",
        ),
        migrations.RenameField(
            model_name="asset",
            old_name="supplier_cost",
            new_name="purchase_cost",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="supplier_date",
        ),
        migrations.AddField(
            model_name="asset",
            name="serial_no",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="asset",
            name="supplied_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="asset",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
