# Generated by Django 5.2 on 2025-05-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('deployed', 'Deployed'), ('pending', 'Pending'), ('in-progress', 'In-progress')], default='Pending', max_length=255),
        ),
    ]
