# Generated by Django 5.2 on 2025-05-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('deployed', 'Deployed'), ('pending', 'Pending'), ('undeployed', 'undeployed')], default='Pending', max_length=255),
        ),
    ]
