# Generated by Django 5.2 on 2025-05-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('disposal', 'Disposal'), ('good', 'Good'), ('damaged', 'Damaged')], default='Good', max_length=255),
        ),
    ]
